require_relative './cyrus-code-challenge/version'
require_relative './cyrus-code-challenge/cli-helpers'
require_relative './cyrus-code-challenge/cli'
require_relative './cyrus-code-challenge/printer'
require_relative './cyrus-code-challenge/contacts-creator'
require_relative './cyrus-code-challenge/contacts'
require_relative './cyrus-code-challenge/formatter'
require_relative './cyrus-code-challenge/parser'
